version: '3'
services:
  qrapp:
    build:
      context: ../../
      dockerfile: scripts/docker/images/Dockerfile.nodeapp
    ports:
      - ${QR_APP_PORT}:3000
    environment:
      - NODE_ENV=${APP_ENVIRONMENT}
      - TZ=${APP_TIMEZONE}
      - LANG=${APP_LANG}
      - APP_ENV=${APP_ENVIRONMENT}
      - APP_DEBUG=${APP_DEBUG}
      - APP_LOG_LEVEL=${APP_LOG_LEVEL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - DYNAMODB_DATABASE_ENDPOINT=${DYNAMODB_DATABASE_ENDPOINT_HOST_INTERNAL}
      - DYNAMO_TABLE_NAME=${DYNAMO_TABLE_NAME}
      - QR_APP_PORT=${QR_APP_PORT}
    networks:
      - qrnetwork

networks:
  qrnetwork:
    driver: bridge
